/*Question 1*/

SELECT COUNT(*) - COUNT(DISTINCT CITY) AS DIFF_OF_CITIES
FROM STATION;


/*Question 2*/
SELECT DISTINCT CITY
FROM STATION
WHERE NOT (CITY LIKE 'A%' OR CITY LIKE 'E%' OR CITY LIKE 'I%' OR CITY LIKE 'O%' OR CITY LIKE 'U%')
  OR NOT (CITY LIKE '%a' OR CITY LIKE '%e' OR CITY LIKE '%i' OR CITY LIKE '%o' OR CITY LIKE '%u');


/*Question 3*/

select * 
FROM STUDENTS
WHERE Marks > 75
ORDER BY NOT(Name LIKE '%bby' ) ASC;


/*Question 4*/
SELECT name
FROM Employee
WHERE salary > 2000 AND months < 10
ORDER BY employee_id ASC; 

/* Question 5 */
SELECT *
FROM CITY;


